/**
 * Minimal POC catalogue. GLBs are generated by cad-worker/scripts/make_furniture.py:
 * metres, Y-up, origin on the floor at the footprint centre, so scale stays 1 and position.y = 0.
 */
export type FurnitureAsset = {
  id: string;
  name: string;
  modelUrl: string;
  width: number;
  depth: number;
  height: number;
};

export const FURNITURE_CATALOG: FurnitureAsset[] = [
  { id: "sofa-001", name: "Sofa", modelUrl: "/furniture/sofa.glb", width: 2.2, depth: 0.9, height: 0.8 },
  { id: "bed-001", name: "Bed", modelUrl: "/furniture/bed.glb", width: 1.6, depth: 2.1, height: 1.0 },
  { id: "dining-table-001", name: "Dining Table", modelUrl: "/furniture/dining-table.glb", width: 1.6, depth: 0.9, height: 0.75 },
];

export function findAsset(assetId: string): FurnitureAsset | undefined {
  return FURNITURE_CATALOG.find((asset) => asset.id === assetId);
}
